spring:
  application:
    name: lcwd_substringFoodies

  app:
    base-url: http://localhost:8063

  datasource:
    url: jdbc:mysql://localhost:3306/lcwd_food_delivery_app
    username: root
    password: Restinpeace11.

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    user:
      name: user
      password: user

logging:
  level:
    org:
      springframework:
        security: DEBUG

razorpay:
  key_id: rzp_test_S2bLEGfYT1Naqo9
  key_secret: 6zkwpiURzetLG1H53sL5lPsO

jwt:
  secret: sdfasdvsdagbfkjadfkjsgksdfgjkgjkg

restaurant:
  file:
    path: uploads/restaurant_banner/

food:
  file:
    path: uploads/food_item_banner/

server:
  port: 8062
