spring:
  application:
    name: lcwd_substringFoodies

  mail:
    host: smtp.gmail.com
    port: 587
    username: my_username@gmail.com
    password: my_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  app:
    base-url: http://localhost:8063

  datasource:
    url: jdbc:mysql://localhost:3306/lcwd_food_delivery_app
    username: my_username
    password: my_password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    user:
      name: user
      password: user

logging:
  level:
    org:
      springframework:
        security: DEBUG

razorpay:
  key_id: rzp_test_S2bLEGfYT1Naqo9
  key_secret: your_key_secret

jwt:
  secret: my_jwt_secret_key

restaurant:
  file:
    path: uploads/restaurant_banner/

food:
  file:
    path: uploads/food_item_banner/

server:
  port: 8062
