spring:
  application:
    name: lcwd_substringFoodies

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#  security:
#    user:
#      name: ${SECURITY_USERNAME}
#      password: ${SECURITY_PASSWORD}

logging:
  level:
    org:
      springframework:
        security: DEBUG

razorpay:
  key_id: ${RAZORPAY_KEY_ID}
  key_secret: ${RAZORPAY_KEY_SECRET}

jwt:
  secret: ${JWT_SECRET}

restaurant:
  file:
    path: uploads/restaurant_banner/

server:
  port: 8062
