spring:
  application:
    name: lcwd_substringFoodies

  datasource:
    url: jdbc:mysql://localhost:3306/lcwd_food_delivery_app

    # This below URL helps your app in docker to communicate with the DB in your host machine.
    # url: jdbc:mysql://host.docker.internal:3306/lcwd

    username: root
    password: Restinpeace11.

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  # File_upload_Configurations
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  security:
    user:
      name: user
      password: user

logging:
  level:
    org.springframework.security: DEBUG

restaurant:
  file:
    path: uploads/restaurant_banner/

razorpay:
  key_id: rzp_test_gSTSCaNRmkjT5L
  key_secret: 3IVGEg5yBOaR67BlrPVa5nvj

server:
  port: 8062

jwt:
  secret: sdfasdvsdagbfkjadfkjsgksdfgjkgjkg
